# Generated by Django 6.0.3 on 2026-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefolder',
            name='resource_type',
            field=models.CharField(choices=[('sensor', '传感器'), ('device', '设备'), ('automation', '自动化规则')], db_index=True, max_length=10, verbose_name='资源类型'),
        ),
    ]
