# Generated by Django 6.0.3 on 2026-07-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_remove_devicestatuscollection_devices_dev_timesta_e69fed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatuscollection',
            name='message_id',
            field=models.CharField(blank=True, help_text='设备可选上报；同一设备内用于去重 QoS 重投消息', max_length=128, null=True, verbose_name='MQTT 消息幂等 ID'),
        ),
        migrations.AddConstraint(
            model_name='devicestatuscollection',
            constraint=models.UniqueConstraint(fields=('device', 'message_id'), name='uniq_device_status_msg'),
        ),
    ]
