# Generated by Django 6.0.3 on 2026-07-16 01:07

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def clear_future_last_seen(apps, schema_editor):
    """旧版本曾信任设备时间；明显未来值无法证明在线，按离线清理。"""
    Sensor = apps.get_model('sensors', 'Sensor')
    Sensor.objects.filter(
        last_seen__gt=timezone.now() + timedelta(minutes=5)
    ).update(last_seen=None, is_online=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_sensor_mqtt_topic_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensordata',
            name='sensors_sen_timesta_a94ae6_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorstatuscollection',
            name='sensors_sen_timesta_bf99ae_idx',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最后上报时间'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='服务器接收到数据的时间', verbose_name='接收时间'),
        ),
        migrations.AlterField(
            model_name='sensorstatuscollection',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='服务器接收到数据的时间', verbose_name='接收时间'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor', '-received_at'], name='sensor_data_recv_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorstatuscollection',
            index=models.Index(fields=['sensor', '-received_at'], name='sensor_recv_latest_idx'),
        ),
        migrations.RunPython(clear_future_last_seen, migrations.RunPython.noop),
    ]
