# Generated by Django 6.0.3 on 2026-07-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_remove_sensordata_sensors_sen_timesta_a94ae6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='message_id',
            field=models.CharField(blank=True, help_text='设备可选上报；同一传感器内用于去重 QoS 重投消息', max_length=128, null=True, verbose_name='MQTT 消息幂等 ID'),
        ),
        migrations.AddField(
            model_name='sensorstatuscollection',
            name='message_id',
            field=models.CharField(blank=True, help_text='设备可选上报；同一传感器内用于去重 QoS 重投消息', max_length=128, null=True, verbose_name='MQTT 消息幂等 ID'),
        ),
        migrations.AddConstraint(
            model_name='sensordata',
            constraint=models.UniqueConstraint(fields=('sensor', 'message_id'), name='uniq_sensor_data_msg'),
        ),
        migrations.AddConstraint(
            model_name='sensorstatuscollection',
            constraint=models.UniqueConstraint(fields=('sensor', 'message_id'), name='uniq_sensor_status_msg'),
        ),
    ]
