"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import math
import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须通过环境变量 SECRET_KEY 传入，开发环境使用固定值
_env_secret = os.environ.get("SECRET_KEY", "")
if _env_secret:
    SECRET_KEY = _env_secret
else:
    # 仅在 DEBUG=True 时允许使用开发默认值
    _dev_debug = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")
    if _dev_debug:
        SECRET_KEY = "django-insecure-dev-only-key-do-not-use-in-production"
    else:
        raise ImproperlyConfigured(
            "生产环境必须设置 SECRET_KEY 环境变量！"
            "请运行: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# 允许的主机，逗号分隔，如: localhost,127.0.0.1,yourdomain.com
_allowed = os.environ.get("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",")] if _allowed else ["*"]


# Application definition

INSTALLED_APPS = [
    # daphne 必须放在 staticfiles 之前，否则 runserver 不会接管 ASGI（Channels 文档明确要求）
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方应用
    "channels",
    "corsheaders",
    "django_extensions",  # Django Extensions
    "rest_framework",
    "rest_framework_simplejwt",  # JWT 认证
    # 本地应用
    "devices",
    "sensors",
    "automation",
    "projects",
    "resource_folders",
    "platform_settings",
    "services.realtime.apps.RealtimeConfig",
]

# 自动发现 plugins/ 子目录下的插件 app
# 注：所有发现到的插件都会加入 INSTALLED_APPS，保证 makemigrations 正常工作
# 是否真正暴露 API 由 urls.py 按 Plugin.enabled 过滤
try:
    from plugins import discover_plugins as _discover_plugins
    INSTALLED_APPS.extend(p.app_label for p in _discover_plugins())
except Exception as _e:  # pragma: no cover - 启动期间不应阻断
    import sys as _sys
    print(f"[plugins] 发现失败，已跳过: {_e}", file=_sys.stderr)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS中间件，需要放在前面
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# test/local/prod 必须使用不同 namespace，避免宿主机暴露的生产 Redis 被本地
# manage.py 或测试误写。测试使用纯内存 layer，完全不访问 Redis。
IS_TESTING = (
    os.environ.get("DJANGO_TESTING", "").lower() in ("true", "1", "yes")
    or "test" in sys.argv
)
_is_mysql_runtime = os.environ.get("DB_USE_MYSQL", "").lower() in (
    "true",
    "1",
    "yes",
)
_configured_runtime_env = os.environ.get("IOT_RUNTIME_ENV", "").strip().lower()
if IS_TESTING:
    IOT_RUNTIME_ENV = "test"
elif _configured_runtime_env:
    if _configured_runtime_env not in ("local", "production"):
        raise ImproperlyConfigured(
            "IOT_RUNTIME_ENV 必须是 local 或 production"
        )
    IOT_RUNTIME_ENV = _configured_runtime_env
else:
    # 兼容既有部署：未显式设置时，MySQL 仍按生产模式处理；新部署应明确设置，
    # 避免“本地连接 MySQL”被误判为生产进程并共用 Redis namespace。
    IOT_RUNTIME_ENV = "production" if _is_mysql_runtime else "local"
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")
if IS_TESTING:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
            "CONFIG": {
                "capacity": 1500,
                "expiry": 30,
            },
        }
    }
else:
    _channel_prefix_default = (
        "asgi" if IOT_RUNTIME_ENV == "production" else "spr_iot_local"
    )
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
                "prefix": os.environ.get(
                    "CHANNEL_LAYER_PREFIX",
                    _channel_prefix_default,
                ),
                "capacity": 1500,
                "expiry": 30,
            },
        }
    }

# 实时通知是可恢复的瞬时状态，使用有界、按资源合并的进程内发送缓冲区。
REALTIME_DISPATCH_QUEUE_CAPACITY = int(
    os.environ.get("REALTIME_DISPATCH_QUEUE_CAPACITY", "512")
)
REALTIME_DISPATCH_QUEUE_MAX_BYTES = int(
    os.environ.get(
        "REALTIME_DISPATCH_QUEUE_MAX_BYTES",
        str(16 * 1024 * 1024),
    )
)
if not 32 <= REALTIME_DISPATCH_QUEUE_CAPACITY <= 10000:
    raise ImproperlyConfigured(
        "REALTIME_DISPATCH_QUEUE_CAPACITY 必须在 32 到 10000 之间"
    )
if not 1024 * 1024 <= REALTIME_DISPATCH_QUEUE_MAX_BYTES <= 256 * 1024 * 1024:
    raise ImproperlyConfigured(
        "REALTIME_DISPATCH_QUEUE_MAX_BYTES 必须在 1048576 到 268435456 之间"
    )

# MQTT 跨进程命令总线（Redis Streams）。只有独立 mqtt_runner 持有
# Paho client；ASGI worker 在 Redis 不可用时 fail closed，不回退为进程内直连。
if IS_TESTING:
    _mqtt_bus_prefix_default = f"spr:iot:mqtt:test:{os.getpid()}"
elif IOT_RUNTIME_ENV == "production":
    _mqtt_bus_prefix_default = "spr:iot:mqtt"
else:
    _mqtt_bus_prefix_default = "spr:iot:mqtt:local"
MQTT_BUS_PREFIX = (
    _mqtt_bus_prefix_default
    if IS_TESTING
    else os.environ.get("MQTT_BUS_PREFIX", _mqtt_bus_prefix_default)
)
MQTT_COMMAND_BROKER_ACK_TIMEOUT = float(
    os.environ.get("MQTT_COMMAND_BROKER_ACK_TIMEOUT", "2")
)
if (
    not math.isfinite(MQTT_COMMAND_BROKER_ACK_TIMEOUT)
    or MQTT_COMMAND_BROKER_ACK_TIMEOUT < 0.1
    or MQTT_COMMAND_BROKER_ACK_TIMEOUT > 30
):
    raise ImproperlyConfigured(
        "MQTT_COMMAND_BROKER_ACK_TIMEOUT 必须在 0.1 到 30 秒之间"
    )
MQTT_COMMAND_RESULT_TTL = int(os.environ.get("MQTT_COMMAND_RESULT_TTL", "600"))
MQTT_CHECK_CODE_TTL = int(os.environ.get("MQTT_CHECK_CODE_TTL", "120"))
MQTT_RUNNER_STATUS_TTL = int(os.environ.get("MQTT_RUNNER_STATUS_TTL", "15"))
MQTT_RUNNER_LEASE_TTL = int(os.environ.get("MQTT_RUNNER_LEASE_TTL", "20"))
MQTT_DEAD_LETTER_MAXLEN = int(
    os.environ.get("MQTT_DEAD_LETTER_MAXLEN", "10000")
)
MQTT_DEAD_LETTER_MAX_PAYLOAD_BYTES = int(
    os.environ.get("MQTT_DEAD_LETTER_MAX_PAYLOAD_BYTES", str(64 * 1024))
)
MQTT_INBOUND_MAX_PAYLOAD_BYTES = int(
    os.environ.get("MQTT_INBOUND_MAX_PAYLOAD_BYTES", str(256 * 1024))
)
if not 1 <= MQTT_DEAD_LETTER_MAX_PAYLOAD_BYTES <= 1024 * 1024:
    raise ImproperlyConfigured(
        "MQTT_DEAD_LETTER_MAX_PAYLOAD_BYTES 必须在 1 到 1048576 之间"
    )
if not 1 <= MQTT_INBOUND_MAX_PAYLOAD_BYTES <= 16 * 1024 * 1024:
    raise ImproperlyConfigured(
        "MQTT_INBOUND_MAX_PAYLOAD_BYTES 必须在 1 到 16777216 之间"
    )
MQTT_BUS_REDIS_CONNECT_TIMEOUT = float(
    os.environ.get("MQTT_BUS_REDIS_CONNECT_TIMEOUT", "1")
)
# 必须大于默认 3 秒设备确认等待，否则 BLPOP 会被 socket timeout 提前打断。
MQTT_BUS_REDIS_SOCKET_TIMEOUT = float(
    os.environ.get("MQTT_BUS_REDIS_SOCKET_TIMEOUT", "10")
)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 通过环境变量切换：未设置 DB_USE_MYSQL 或为空时使用 SQLite

if os.environ.get("DB_USE_MYSQL", "").lower() in ("true", "1", "yes"):
    try:
        _db_connect_timeout = int(os.environ.get("DB_CONNECT_TIMEOUT", "5"))
    except (TypeError, ValueError) as _db_timeout_error:
        raise ImproperlyConfigured(
            "DB_CONNECT_TIMEOUT 必须是整数"
        ) from _db_timeout_error
    if not 1 <= _db_connect_timeout <= 30:
        raise ImproperlyConfigured(
            "DB_CONNECT_TIMEOUT 必须在 1 到 30 秒之间"
        )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", "iot_platform"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            # 复用短时 MySQL 连接，避免每个 API/MQTT 回调重复握手；使用前先
            # 健康探测，服务端 wait_timeout 关闭连接后可自动换新。
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES', default_storage_engine=INNODB",
                "connect_timeout": _db_connect_timeout,
            },
        }
    }
else:
    _sqlite_path = os.environ.get("SQLITE_DB_PATH")
    _db_name = _sqlite_path if _sqlite_path else str(BASE_DIR / "db.sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _db_name,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 中文简体

TIME_ZONE = "Asia/Shanghai"  # 中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Whitenoise 在 Gunicorn 下提供 Admin 等静态文件

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# CORS配置 - 允许前端访问
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vue.js开发服务器
    "http://localhost:3000",
    "http://localhost:48080",  # Docker 前端默认端口
    "http://localhost:48081",  # Docker Admin 直连默认端口
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:48080",
    "http://127.0.0.1:48081",
]

# 支持通过环境变量追加额外的 CORS 源（逗号分隔）
_extra_cors = os.environ.get("EXTRA_CORS_ORIGINS", "")
if _extra_cors:
    CORS_ALLOWED_ORIGINS.extend(o.strip() for o in _extra_cors.split(",") if o.strip())

CORS_ALLOW_CREDENTIALS = True

# 生产环境安全配置
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "False").lower() in ("true", "1")
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False").lower() in ("true", "1")

# CSRF 可信来源（与 CORS 配合，用于跨域 POST 等请求）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:48080",
    "http://localhost:48081",  # Docker Admin 直连默认端口
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:48080",
    "http://127.0.0.1:48081",
    # 开发时若从局域网设备访问，请添加如 "http://192.168.x.x:5173"
]

# 支持通过环境变量追加反向代理/公网域名（必须包含 http:// 或 https://，逗号分隔）。
# 与 EXTRA_CORS_ORIGINS 分开配置：Django Admin 的同源表单通常只需要 CSRF trusted origin，
# 不需要额外开放跨域 API 访问。
_extra_csrf_origins = os.environ.get("EXTRA_CSRF_TRUSTED_ORIGINS", "")
if _extra_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(
        origin.strip()
        for origin in _extra_csrf_origins.split(",")
        if origin.strip()
    )

# MQTT 与设备配置：仅从 platform_settings 数据库读取
# 使用 SimpleLazyObject 延迟读取，避免 settings 加载时 DB 未就绪
# 启动前由 sensors.apps 自动执行 `configure --init --no-reload` 把 defaults.py 中的默认值写入 DB
from django.utils.functional import SimpleLazyObject
from config.platform_config import get_config

def _lazy_config(key, default, value_type=str):
    return SimpleLazyObject(lambda: get_config(key, default, value_type))

MQTT_BROKER = _lazy_config("mqtt_broker", "127.0.0.1")
MQTT_PORT = _lazy_config("mqtt_port", 1883, int)
MQTT_KEEPALIVE = _lazy_config("mqtt_keepalive", 60, int)
MQTT_USERNAME = _lazy_config("mqtt_username", "")
MQTT_PASSWORD = _lazy_config("mqtt_password", "")

# MQTT主题配置
MQTT_TOPICS = {
    "SENSOR_DATA": "iot/sensors/+/data",  # 传感器数据上报主题
    "SENSOR_STATUS": "iot/sensors/+/status",  # 传感器状态上报主题
    "SENSOR_CONTROL": "iot/sensors/+/control",  # 传感器控制主题
    "DEVICE_CONTROL": "iot/devices/+/control",  # 设备控制主题
    "DEVICE_STATUS": "iot/devices/+/status",  # 设备状态反馈主题
}

# 设备离线检测配置（秒）
DEVICE_OFFLINE_TIMEOUT = _lazy_config("device_offline_timeout", 300, int)
DEVICE_RECONNECT_ATTEMPTS = _lazy_config("device_reconnect_attempts", 3, int)
DEVICE_RECONNECT_INTERVAL = _lazy_config("device_reconnect_interval", 10, int)

# 默认主键字段类型
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '5000/hour',
    },
}

# SimpleJWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),      # Access Token 有效期 2 小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Refresh Token 有效期 7 天
    'ROTATE_REFRESH_TOKENS': True,                     # 刷新时轮换 Refresh Token
    'BLACKLIST_AFTER_ROTATION': False,                  # 轮换后不加入黑名单（无需blacklist app）
    'AUTH_HEADER_TYPES': ('Bearer',),                   # Authorization: Bearer <token>
}

# 自定义 Python 自动化属于高风险能力：独立子进程可硬终止，但不是 OS 沙箱。
# 只有完全信任超级用户且明确接受容器内代码执行风险时，才可通过环境变量开启。
AUTOMATION_SCRIPT_EXECUTION_ENABLED = os.environ.get(
    "AUTOMATION_SCRIPT_EXECUTION_ENABLED",
    "False",
).lower() in ("true", "1", "yes")

# 自由脚本在独立子进程中的单拍硬超时。配置错误直接阻止服务启动，不做静默
# 纠正；上限避免一次脚本长期占住 scheduler / Web 请求。
AUTOMATION_SCRIPT_TIMEOUT_MAX_SECONDS = 60.0
_automation_timeout_raw = os.environ.get("AUTOMATION_SCRIPT_TIMEOUT_SECONDS", "10")
try:
    AUTOMATION_SCRIPT_TIMEOUT_SECONDS = float(_automation_timeout_raw)
except (TypeError, ValueError) as _automation_timeout_error:
    raise ImproperlyConfigured(
        "AUTOMATION_SCRIPT_TIMEOUT_SECONDS 必须是数值"
    ) from _automation_timeout_error
if (
    not math.isfinite(AUTOMATION_SCRIPT_TIMEOUT_SECONDS)
    or AUTOMATION_SCRIPT_TIMEOUT_SECONDS <= 0
    or AUTOMATION_SCRIPT_TIMEOUT_SECONDS > AUTOMATION_SCRIPT_TIMEOUT_MAX_SECONDS
):
    raise ImproperlyConfigured(
        "AUTOMATION_SCRIPT_TIMEOUT_SECONDS 必须大于 0 且不超过 "
        f"{AUTOMATION_SCRIPT_TIMEOUT_MAX_SECONDS:g} 秒"
    )

# 手动 API、Admin 与 scheduler 共享 Redis 单飞锁；同一规则只允许一个执行者。
# Redis 不可用时执行器 fail closed，避免多 worker 重复运行自由 Python 脚本。
_automation_lock_prefix_default = (
    f"spr:iot:automation:test:{os.getpid()}:execution"
    if IOT_RUNTIME_ENV == "test"
    else (
        "spr:iot:automation:execution"
        if IOT_RUNTIME_ENV == "production"
        else "spr:iot:automation:local:execution"
    )
)
AUTOMATION_SCRIPT_LOCK_PREFIX = (
    _automation_lock_prefix_default
    if IS_TESTING
    else os.environ.get(
        "AUTOMATION_SCRIPT_LOCK_PREFIX",
        _automation_lock_prefix_default,
    )
)

# 执行进程启动方式：auto 在支持的平台使用预加载 Django 的 forkserver，否则
# 回退 spawn。线上出现兼容问题时可设为 spawn 一键回滚，不改变脚本隔离语义。
AUTOMATION_EXECUTOR_START_METHOD = os.environ.get(
    "AUTOMATION_EXECUTOR_START_METHOD",
    "auto",
).strip().lower()
if AUTOMATION_EXECUTOR_START_METHOD not in ("auto", "forkserver", "spawn"):
    raise ImproperlyConfigured(
        "AUTOMATION_EXECUTOR_START_METHOD 必须是 auto、forkserver 或 spawn"
    )

# 自动化规则脚本允许导入的模块白名单。
# 这只是开启脚本后的纵深防御，不是 Python 安全沙箱，不能替代进程/容器隔离。
# 格式：逗号分隔的模块名列表。
AUTOMATION_ALLOWED_IMPORTS = os.environ.get(
    "AUTOMATION_ALLOWED_IMPORTS",
    "time,datetime,math,random,json,re"
).split(",")

# 日志配置（定义于 config/logging_config.py）
from config.logging_config import LOGGING
