# Generated by Django 6.0.3 on 2026-03-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('script_id', models.CharField(help_text="唯一标识，通过 execute_by_script_id('xxx') 调用执行，如 humidity_overflow_print、humidity_alert", max_length=50, unique=True, verbose_name='脚本唯一ID')),
                ('script', models.TextField(blank=True, help_text='\n        Python 脚本，Arduino 风格：from engine import sensors, devices，定义带 loop() 的控制器类。\n\n        engine 由引擎注入，含 sensors、devices。控制器类 __init__ 相当于 setup()，loop() 返回 True/False。\n\n        参见 automation/script/sample_file.txt 完整示例。\n        ', verbose_name='脚本')),
                ('device_list', models.JSONField(default=list, help_text='\n        脚本中可访问的设备和传感器，device_id 需与 devices.Device 或 sensors.Sensor 表中的 device_id 对应。\n        格式示例：\n        [\n            {"device_id": "DHT11-WEMOS-001", "device_type": "Sensor", "name": "温湿度传感器"},\n            {"device_id": "SG_80_01", "device_type": "Device", "name": "LED灯"}\n        ]\n        ', verbose_name='设备与传感器列表')),
                ('is_launched', models.BooleanField(default=False, help_text='标记该规则是否应持续轮询执行', verbose_name='是否启动轮询')),
                ('poll_interval', models.PositiveIntegerField(default=30, help_text='轮询执行的时间间隔，单位为秒，最小 1 秒', verbose_name='轮询间隔（秒）')),
                ('process_status', models.CharField(choices=[('idle', '未启动'), ('running', '正在运行'), ('stopped_by_user', '由用户停止'), ('error_stopped', '由错误停止')], default='idle', max_length=20, verbose_name='进程状态')),
                ('error_message', models.TextField(blank=True, help_text='当 process_status 为 error_stopped 时的错误详情', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '自动化规则',
                'verbose_name_plural': '自动化规则',
                'ordering': ['-created_at'],
            },
        ),
    ]
