# Generated by Django 6.0.3 on 2026-06-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationrule_last_run_time'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='project',
            field=models.ForeignKey(blank=True, help_text='留空表示全局规则（不归属任何项目）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='script',
            field=models.TextField(blank=True, help_text='\n        Python 脚本，两种写法均可：\n        1. 类风格：定义含 loop() 方法的类，引擎自动实例化并调用\n        2. 函数风格：直接定义顶层 loop() 函数\n\n        from engine import sensors, devices（由引擎注入）\n        loop() 返回 True 表示执行成功，False 表示条件未满足。\n\n        完整示例参见 docs/backend/backend_design/AutomationRules_design.md\n        ', verbose_name='脚本'),
        ),
    ]
