# Generated by Django 6.0.3 on 2026-06-25 10:21

import automation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automationrule_project_alter_automationrule_script'),
        ('projects', '0002_section_scoped'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('description', models.TextField(blank=True, verbose_name='方案描述')),
                ('data_key', models.CharField(blank=True, help_text='从传感器最新数据中取哪个字段作为 PV；留空则用传感器成员的 data_key', max_length=50, verbose_name='数据字段')),
                ('control_type', models.CharField(choices=[('on_off', '双位控制'), ('pi', '比例积分(PI)'), ('pid', 'PID控制')], default='on_off', max_length=10, verbose_name='控制类型')),
                ('setpoint', models.FloatField(default=0.0, verbose_name='设定值（SP）')),
                ('action', models.CharField(choices=[('heat', '正作用（PV 低于 SP 时增大输出/开，如加热）'), ('cool', '反作用（PV 高于 SP 时增大输出/开，如降温开阀）')], default='cool', max_length=10, verbose_name='作用方向')),
                ('sample_interval', models.PositiveIntegerField(default=5, help_text='后台多久执行一次控制计算，最小 1 秒', verbose_name='控制周期（秒）')),
                ('output_mode', models.CharField(choices=[('analog', '模拟量（下发数值，如舵机角度/阀门开度%）'), ('switch', '开关量（开/关命令）')], default='switch', max_length=10, verbose_name='输出方式')),
                ('params', models.JSONField(blank=True, default=dict, help_text='结构示例：{deadband, kp, ki, kd, out_min, out_max, analog:{command, param, range_min, range_max}, switch:{on_command, off_command, convert(threshold|pwm), pwm_period}}', verbose_name='算法参数与输出映射')),
                ('runtime_state', models.JSONField(blank=True, default=automation.models._default_runtime_state, help_text='integral / prev_error / on / pwm_phase，每拍更新', verbose_name='控制器内部运行态')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用控制环')),
                ('status', models.CharField(choices=[('idle', '未启用'), ('running', '运行中'), ('error', '错误停止')], default='idle', max_length=10, verbose_name='运行状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('last_pv', models.FloatField(blank=True, null=True, verbose_name='最近实测值')),
                ('last_output', models.FloatField(blank=True, null=True, verbose_name='最近控制输出')),
                ('last_command', models.CharField(blank=True, max_length=200, verbose_name='最近下发命令')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_schemes', to='projects.projectdevicemember', verbose_name='执行器设备')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_schemes', to='projects.project', verbose_name='所属项目')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_schemes', to='projects.projectsection', verbose_name='所属房间')),
                ('sensor_member', models.ForeignKey(help_text='被删除前需先解绑控制方案，避免静默失控', on_delete=django.db.models.deletion.PROTECT, related_name='control_schemes', to='projects.projectsensormember', verbose_name='被控量传感器（PV）')),
            ],
            options={
                'verbose_name': '控制方案',
                'verbose_name_plural': '控制方案',
                'ordering': ['-created_at'],
            },
        ),
    ]
