# Generated by Django 6.0.3 on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_controlscheme'),
        ('projects', '0002_section_scoped'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='section',
            field=models.ForeignKey(
                blank=True,
                help_text='项目脚本必须归属一个房间；可用资源仅限该房间已导入成员',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='automation_rules',
                to='projects.projectsection',
                verbose_name='所属房间',
            ),
        ),
    ]
