# Generated by Django 6.0.3 on 2026-07-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_automationrule_section'),
        ('resource_folders', '0002_alter_resourcefolder_resource_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '自动化规则', 'verbose_name_plural': '自动化规则'},
        ),
        migrations.AddField(
            model_name='automationrule',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='resource_folders.resourcefolder', verbose_name='管理文件夹'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='显示顺序'),
        ),
    ]
